name: Docker Image CI

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]
jobs:
  build:
    runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.PACKAGE_TOKEN }}
- name: Build the Join-Bot Docker image
run: |
       docker build . --tag ghcr.io/brockbreacher/join-bot:latest
       docker push ghcr.io/brockbreacher/join-bot:latest
