name: Stable Docker Image

on:
 workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.OWNER_NAME }}
          password: ${{ secrets.PACKAGE_TOKEN }}
          
      - name: Build the Join-Bot Docker image
        run: |
          docker build . --tag ghcr.io/brockbreacher/join-bot:stable
          docker push ghcr.io/brockbreacher/join-bot:stable
